# Generated by Django 2.1.4 on 2019-01-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersprofile',
            options={'verbose_name': '用户个人信息', 'verbose_name_plural': '用户个人信息'},
        ),
        migrations.AlterModelTable(
            name='usersprofile',
            table='tb_users_profile',
        ),
    ]
